// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package logic

import (
	_ "github.com/leapord/prometheusx/internal/logic/config"
	_ "github.com/leapord/prometheusx/internal/logic/group"
	_ "github.com/leapord/prometheusx/internal/logic/node"
	_ "github.com/leapord/prometheusx/internal/logic/rules"
	_ "github.com/leapord/prometheusx/internal/logic/user"
)
