// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
)

// Config is the golang structure of table config for DAO operations like Where/Data.
type Config struct {
	g.Meta `orm:"table:config, do:true"`
	Id     interface{} // 主键
	Name   interface{} // 配置名称
	Value  interface{} // 配置内容
}
