// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
)

// Group is the golang structure of table group for DAO operations like Where/Data.
type Group struct {
	g.Meta         `orm:"table:group, do:true"`
	Id             interface{} // 主键
	Name           interface{} // 分组名称
	Identification interface{} // 英文标识
	CreateTime     interface{} // 创建时间
}
