// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// Rules is the golang structure of table rules for DAO operations like Where/Data.
type Rules struct {
	g.Meta     `orm:"table:rules, do:true"`
	Id         interface{} // 主键
	GroupName  interface{} // 规则组名称
	Type       interface{} // 规则类型 alert record
	Content    interface{} // 规则内容
	Active     interface{} // 是否启用
	CreateTime *gtime.Time // 创建时间
}
