// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// User is the golang structure of table user for DAO operations like Where/Data.
type User struct {
	g.Meta      `orm:"table:user, do:true"`
	Id          interface{} // 主键
	Name        interface{} // 用户名
	LoginName   interface{} // 登录名
	Password    interface{} // 登录密码,MD5加密
	CreateTime  *gtime.Time // 创建时间
	Email       interface{} // 邮箱
	PhoneNumber interface{} // 手机号码
}
