// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

import (
	"context"

	"github.com/gogf/gf/v2/database/gdb"
	"github.com/gogf/gf/v2/frame/g"
)

// AlertDao is the data access object for table alert.
type AlertDao struct {
	table   string       // table is the underlying table name of the DAO.
	group   string       // group is the database configuration group name of current DAO.
	columns AlertColumns // columns contains all the column names of Table for convenient usage.
}

// AlertColumns defines and stores column names for table alert.
type AlertColumns struct {
	Id           string // 主键
	GroupKey     string // key identifying the group of alerts (e.g. to deduplicate)
	Status       string // resolved|firing
	ExternalUrl  string // alertmanager连接
	Labels       string // 告警labels
	Annotations  string // 告警annotations
	StartsAt     string // 告警开始时间
	EndsAt       string // 告警结束时间
	GeneratorUrl string // 触发告警连接
	Fingerprint  string // 告警指纹
	CreateTime   string // 创建时间
}

//  alertColumns holds the columns for table alert.
var alertColumns = AlertColumns{
	Id:           "id",
	GroupKey:     "group_key",
	Status:       "status",
	ExternalUrl:  "external_url",
	Labels:       "labels",
	Annotations:  "annotations",
	StartsAt:     "starts_at",
	EndsAt:       "ends_at",
	GeneratorUrl: "generator_url",
	Fingerprint:  "fingerprint",
	CreateTime:   "create_time",
}

// NewAlertDao creates and returns a new DAO object for table data access.
func NewAlertDao() *AlertDao {
	return &AlertDao{
		group:   "default",
		table:   "alert",
		columns: alertColumns,
	}
}

// DB retrieves and returns the underlying raw database management object of current DAO.
func (dao *AlertDao) DB() gdb.DB {
	return g.DB(dao.group)
}

// Table returns the table name of current dao.
func (dao *AlertDao) Table() string {
	return dao.table
}

// Columns returns all column names of current dao.
func (dao *AlertDao) Columns() AlertColumns {
	return dao.columns
}

// Group returns the configuration group name of database of current dao.
func (dao *AlertDao) Group() string {
	return dao.group
}

// Ctx creates and returns the Model for current DAO, It automatically sets the context for current operation.
func (dao *AlertDao) Ctx(ctx context.Context) *gdb.Model {
	return dao.DB().Model(dao.table).Safe().Ctx(ctx)
}

// Transaction wraps the transaction logic using function f.
// It rollbacks the transaction and returns the error from function f if it returns non-nil error.
// It commits the transaction and returns nil if function f returns nil.
//
// Note that, you should not Commit or Rollback the transaction in function f
// as it is automatically handled by this function.
func (dao *AlertDao) Transaction(ctx context.Context, f func(ctx context.Context, tx *gdb.TX) error) (err error) {
	return dao.Ctx(ctx).Transaction(ctx, f)
}
