// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

import (
	"context"

	"github.com/gogf/gf/v2/database/gdb"
	"github.com/gogf/gf/v2/frame/g"
)

// RulesDao is the data access object for table rules.
type RulesDao struct {
	table   string       // table is the underlying table name of the DAO.
	group   string       // group is the database configuration group name of current DAO.
	columns RulesColumns // columns contains all the column names of Table for convenient usage.
}

// RulesColumns defines and stores column names for table rules.
type RulesColumns struct {
	Id         string // 主键
	GroupName  string // 规则组名称
	Type       string // 规则类型 alert record
	Content    string // 规则内容
	Active     string // 是否启用
	CreateTime string // 创建时间
}

//  rulesColumns holds the columns for table rules.
var rulesColumns = RulesColumns{
	Id:         "id",
	GroupName:  "group_name",
	Type:       "type",
	Content:    "content",
	Active:     "active",
	CreateTime: "create_time",
}

// NewRulesDao creates and returns a new DAO object for table data access.
func NewRulesDao() *RulesDao {
	return &RulesDao{
		group:   "default",
		table:   "rules",
		columns: rulesColumns,
	}
}

// DB retrieves and returns the underlying raw database management object of current DAO.
func (dao *RulesDao) DB() gdb.DB {
	return g.DB(dao.group)
}

// Table returns the table name of current dao.
func (dao *RulesDao) Table() string {
	return dao.table
}

// Columns returns all column names of current dao.
func (dao *RulesDao) Columns() RulesColumns {
	return dao.columns
}

// Group returns the configuration group name of database of current dao.
func (dao *RulesDao) Group() string {
	return dao.group
}

// Ctx creates and returns the Model for current DAO, It automatically sets the context for current operation.
func (dao *RulesDao) Ctx(ctx context.Context) *gdb.Model {
	return dao.DB().Model(dao.table).Safe().Ctx(ctx)
}

// Transaction wraps the transaction logic using function f.
// It rollbacks the transaction and returns the error from function f if it returns non-nil error.
// It commits the transaction and returns nil if function f returns nil.
//
// Note that, you should not Commit or Rollback the transaction in function f
// as it is automatically handled by this function.
func (dao *RulesDao) Transaction(ctx context.Context, f func(ctx context.Context, tx *gdb.TX) error) (err error) {
	return dao.Ctx(ctx).Transaction(ctx, f)
}
