package consts

const (
	JWT_SCRET = "Yb0sQwvNL6LDwO1"
)

const (
	PROMETHEUS_RULE_PATH   = "PROMETHEUS_RULE_PATH"
	PROMETHEUS_TOOL_PATH   = "PROMETHEUS_TOOL_PATH"
	PROMETHEUS_ADMIN_URL   = "PROMETHEUS_ADMIN_URL"
	PROMETHEUS_CONFIG_PATH = "PROMETHEUS_CONFIG_PATH"
)

const (
	STAMP_SERVER_ADDRESS  = "STAMP_SERVER_ADDRESS"
	STAMP_SERVER_PORT     = "STAMP_SERVER_PORT"
	STAMP_SERVER_ACCOUNT  = "STAMP_SERVER_ACCOUNT"
	STAMP_SERVER_PASSWORD = "STAMP_SERVER_PASSWORD"
)

const (
	ALERT_WEB_HOOK_EVENT = "alert_web_hook_event"
	ALERT_MESSAGE_ID     = "alertMessageId"
)
