package consts

const (
	JWT_SCRET            = "Yb0sQwvNL6LDwO1"
	PROMETHEUS_RULE_PATH = "PROMETHEUS_RULE_PATH"
	PROMETHEUS_TOOL_PATH = "PROMETHEUS_TOOL_PATH"
	PROMETHEUS_ADMIN_URL = "PROMETHEUS_ADMIN_URL"
)
