// ================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// You can delete these comments if you wish manually maintain this interface file.
// ================================================================================

package service

import (
	"context"

	model "github.com/leapord/prometheusx/internal/model/do"
	"github.com/leapord/prometheusx/internal/model/entity"
)

type IConfig interface {
	Add(ctx context.Context, config model.Config) (result entity.Config, err error)
	Update(ctx context.Context, config model.Config) (result entity.Config, err error)
	Remove(ctx context.Context, id int) (config entity.Config, err error)
	Detail(ctx context.Context, id int) (config entity.Config, err error)
	Page(ctx context.Context, pageNo int, pageSize int, config model.Config) (configs []entity.Config, total int, err error)
	NameQuery(ctx context.Context, name string) (result entity.Config, err error)
}

var localConfig IConfig

func Config() IConfig {
	if localConfig == nil {
		panic("implement not found for interface IConfig, forgot register?")
	}
	return localConfig
}

func RegisterConfig(i IConfig) {
	localConfig = i
}
