// ================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// You can delete these comments if you wish manually maintain this interface file.
// ================================================================================

package service

import (
	"context"

	model "github.com/leapord/prometheusx/internal/model/do"
)

type INode interface {
	AddNode(ctx context.Context, node *model.Node) (err error)
	UpdateNode(ctx context.Context, node *model.Node) (err error)
	RemoveNode(ctx context.Context, id int) (node model.Node, err error)
	DetailNode(ctx context.Context, id int) (node model.Node, err error)
	Page(ctx context.Context, pageNo int, pageSize int, node model.Node) (total int, models []model.Node, err error)
	Active(ctx context.Context, id int, active bool) (err error)
	Target(ctx context.Context) (result string, err error)
}

var localNode INode

func Node() INode {
	if localNode == nil {
		panic("implement not found for interface INode, forgot register?")
	}
	return localNode
}

func RegisterNode(i INode) {
	localNode = i
}
