// ================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// You can delete these comments if you wish manually maintain this interface file.
// ================================================================================

package service

import (
	"context"

	model "github.com/leapord/prometheusx/internal/model/do"
	"github.com/leapord/prometheusx/internal/model/entity"
)

type IRules interface {
	Add(ctx context.Context, rules model.Rules) (result entity.Rules, err error)
	Update(ctx context.Context, rules model.Rules) (rule entity.Rules, err error)
	Remove(ctx context.Context, id int) (rules entity.Rules, err error)
	Detail(ctx context.Context, id int) (rules entity.Rules, err error)
	Page(ctx context.Context, pageNo int, pageSize int, rules model.Rules) (models []entity.Rules, total int, err error)
	GeneratedFile(ctx context.Context) (err error)
	Active(ctx context.Context, id int, active bool) (err error)
}

var localRules IRules

func Rules() IRules {
	if localRules == nil {
		panic("implement not found for interface IRules, forgot register?")
	}
	return localRules
}

func RegisterRules(i IRules) {
	localRules = i
}
