// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"github.com/leapord/prometheusx/internal/dao/internal"
)

// internalAlertDao is internal type for wrapping internal DAO implements.
type internalAlertDao = *internal.AlertDao

// alertDao is the data access object for table alert.
// You can define custom methods on it to extend its functionality as you wish.
type alertDao struct {
	internalAlertDao
}

var (
	// Alert is globally public accessible object for table alert operations.
	Alert = alertDao{
		internal.NewAlertDao(),
	}
)

// Fill with you ideas below.
