// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"github.com/leapord/prometheusx/internal/dao/internal"
)

// internalNodeDao is internal type for wrapping internal DAO implements.
type internalNodeDao = *internal.NodeDao

// nodeDao is the data access object for table node.
// You can define custom methods on it to extend its functionality as you wish.
type nodeDao struct {
	internalNodeDao
}

var (
	// Node is globally public accessible object for table node operations.
	Node = nodeDao{
		internal.NewNodeDao(),
	}
)

// Fill with you ideas below.
