// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"github.com/leapord/prometheusx/internal/dao/internal"
)

// internalRulesDao is internal type for wrapping internal DAO implements.
type internalRulesDao = *internal.RulesDao

// rulesDao is the data access object for table rules.
// You can define custom methods on it to extend its functionality as you wish.
type rulesDao struct {
	internalRulesDao
}

var (
	// Rules is globally public accessible object for table rules operations.
	Rules = rulesDao{
		internal.NewRulesDao(),
	}
)

// Fill with you ideas below.
