// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

// Config is the golang structure for table config.
type Config struct {
	Id    int64  `json:"id"    ` // 主键
	Name  string `json:"name"  ` // 配置名称
	Value string `json:"value" ` // 配置内容
}
