// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

// Group is the golang structure for table group.
type Group struct {
	Id             int64  `json:"id"             ` // 主键
	Name           string `json:"name"           ` // 分组名称
	Identification string `json:"identification" ` // 英文标识
	CreateTime     string `json:"createTime"     ` // 创建时间
}
